version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  asynqmon:
    image: hibiken/asynqmon
    ports:
      - 8080:8080
    entrypoint: ["./asynqmon"]
    command: ["--redis-url", "redis://:@redis:6379"]

volumes:
  postgres:
  redis:
